language: python
python:
    - "3.6"
before_install:
    - pip install -U pytest
    - pip install -U codecov
install:
	- pip install -r requirements.txt
script:
    - pytest --cov=./tests
after_success:
    - codecov